#!/bin/bash

echo "🚀 Script para instalar Claude Code no servidor Hetzner"
echo "================================================"
echo ""
echo "Execute este script NO SERVIDOR após fazer SSH:"
echo "ssh root@128.140.45.28"
echo ""
echo "Depois copie e cole os comandos abaixo:"
echo ""
echo "# 1. Instalar Node.js 20+ se não estiver instalado"
echo "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
echo "sudo apt-get install -y nodejs"
echo ""
echo "# 2. Instalar Claude Code CLI"
echo "npm install -g @anthropic-ai/claude-code"
echo ""
echo "# 3. Configurar a API key (você precisa da sua API key do Anthropic)"
echo "export ANTHROPIC_API_KEY='sua-api-key-aqui'"
echo ""
echo "# 4. Navegar para o diretório do projeto"
echo "cd /home/teste\\ 1/"
echo ""
echo "# 5. Iniciar o Claude Code"
echo "claude-code"
echo ""
echo "================================================"
echo "ALTERNATIVA: Usar Cursor CLI (mais simples)"
echo "================================================"
echo ""
echo "# 1. Instalar Cursor CLI"
echo "bash <(curl -fsSL https://cursor.sh/install.sh)"
echo ""
echo "# 2. Navegar para o projeto"
echo "cd /home/teste\\ 1/"
echo ""
echo "# 3. Abrir com Cursor"
echo "cursor ."
echo ""
echo "================================================"
echo "Depois de instalar, você pode me dar acesso direto"
echo "ao servidor e eu trabalho diretamente lá!"