#!/bin/bash

# Manual deployment script for Alfalyzer production
# This script provides commands to manually deploy the CORS fix

echo "📋 Alfalyzer Manual Deployment Instructions"
echo "==========================================="
echo ""
echo "This script provides the commands needed to manually deploy the CORS fix."
echo "You'll need to copy and run these commands."
echo ""
echo "🔐 First, SSH into the server:"
echo "   ssh root@128.140.45.28"
echo ""
echo "Once connected, run these commands:"
echo ""
echo "📁 1. Navigate to the project directory:"
echo "   cd '/home/teste 1'"
echo ""
echo "📝 2. Update the CORS middleware file:"
echo "   Create a new cors.ts file with the updated configuration"
echo ""
echo "cat > server/middleware/cors.ts << 'EOF'"
cat server/middleware/cors.ts
echo "EOF"
echo ""
echo "🔨 3. Rebuild the project:"
echo "   npm run build"
echo ""
echo "📂 4. Copy frontend files to the correct location:"
echo "   mkdir -p dist/public"
echo "   cp -r client/dist/public/* dist/public/"
echo ""
echo "🔄 5. Restart PM2:"
echo "   pm2 restart alfalyzer --update-env"
echo "   pm2 save"
echo ""
echo "✅ 6. Verify the deployment:"
echo "   pm2 status"
echo "   curl -s http://localhost:3001/api/health | head -c 200"
echo ""
echo "🌐 7. Test the frontend:"
echo "   Open in browser: https://128.140.45.28.sslip.io/"
echo ""
echo "📊 8. Monitor logs:"
echo "   pm2 logs alfalyzer --lines 100"
echo ""
echo "💡 If CORS still blocks after these steps:"
echo "   echo 'DISABLE_CORS=true' >> .env.production"
echo "   pm2 restart alfalyzer --update-env"
echo ""
echo "==========================================="
echo "Copy the commands above and run them on the server."