import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  blocklist: [
    // Remove unused utility classes
    'prose',
    'prose-sm',
    'prose-lg',
    'prose-xl',
    'prose-2xl',
    'decoration-*',
    'underline-offset-*',
    'text-decoration-*',
    'overflow-ellipsis',
    'overflow-clip',
    'isolation-*',
    'mix-blend-*',
    'bg-blend-*',
    'filter',
    'backdrop-filter',
    'backdrop-blur-*',
    'backdrop-brightness-*',
    'backdrop-contrast-*',
    'backdrop-grayscale-*',
    'backdrop-hue-rotate-*',
    'backdrop-invert-*',
    'backdrop-opacity-*',
    'backdrop-saturate-*',
    'backdrop-sepia-*',
    'supports-*',
    'motion-*',
    'print:*',
    'portrait:*',
    'landscape:*',
    'contrast-*',
    'forced-colors:*',
    'selection:*',
    'marker:*',
    'file:*',
    'placeholder-shown:*',
    'autofill:*',
    'read-only:*',
    'read-write:*',
    'required:*',
    'valid:*',
    'invalid:*',
    'in-range:*',
    'out-of-range:*',
    'default:*',
    'indeterminate:*',
    'target:*',
    'first-of-type:*',
    'last-of-type:*',
    'only-of-type:*',
    'nth-of-type(*):*',
    'nth-last-of-type(*):*',
    'first-letter:*',
    'first-line:*',
    'empty:*',
    'dir(*):*',
    'lang(*):*',
    'not(*):*',
    'is(*):*',
    'where(*):*',
    'has(*):*',
  ],
  safelist: [
    "bg-gradient-to-r",
    "bg-clip-text",
    "text-transparent",
    "text-tangerine",
    "bg-tangerine"
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        positive: "#10b981",
        negative: "#ef4444", 
        neutral: "#f59e0b",
        tangerine: "#f28500",
        "chartreuse": "#D8F22D",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        "glow-pulse": {
          "0%, 100%": {
            boxShadow: "0 0 10px rgba(216, 242, 45, 0.3)",
          },
          "50%": {
            boxShadow: "0 0 25px rgba(216, 242, 45, 0.6)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "glow-pulse": "glow-pulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
