#\!/bin/bash
echo "🚨 FIX URGENTE PARA PRODUÇÃO"
echo "=========================="
echo ""
echo "1. REMOVER VITE_API_URL do Vercel (MAIS IMPORTANTE\!):"
echo "   vercel env rm VITE_API_URL production --yes"
echo ""
echo "2. Verificar que NÃO existe VITE_API_URL em:"
echo "   https://vercel.com/antonios-projects-f9cd3cd0/alfalyzerpro4/settings/environment-variables"
echo ""
echo "3. Fazer redeploy:"
echo "   vercel --prod"
echo ""
echo "NOTA: Sem VITE_API_URL, o frontend usará paths relativos (/api/*)"
echo "      e o Vercel proxy redirecionará para Coolify corretamente."
