#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run tests before push
echo "Running tests before push..."
npm run test -- --passWithNoTests

# Run type check
echo "Running TypeScript check..."
npm run check